"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o0q+jlx75#yz%@e-5&d_xcd&0-b3%wnc5y^8k1w(xmkdha^__l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sorteo'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 👇 MAGIA: Le decimos a Django que lea tu carpeta de plantillas primero 👇
        'DIRS': [BASE_DIR / 'sorteo' / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sorteo.context_processors.metricas_sorteo', # <-- CONEXIÓN CON EL CEREBRO
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Enseñamos a Django a buscar archivos en la carpeta global 'static'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# MAGIA PARA RENDER: La "maleta" donde se guardarán todos los estáticos en producción
STATIC_ROOT = BASE_DIR / 'staticfiles'


# ==========================================
# 🎨 CONFIGURACIÓN DE DISEÑO (JAZZMIN)
# ==========================================
JAZZMIN_SETTINGS = {
    # Títulos en la pestaña del navegador y login
    "site_title": "Admin Sorteo Jared",
    "site_header": "Sorteo Jared",
    
    # Título principal en el menú lateral
    "site_brand": "Sorteos Jared",
    
    # Mensaje de bienvenida en la pantalla de inicio de sesión
    "welcome_sign": "Centro de Comando - Electrodomésticos Jared",
    
    # Texto de derechos de autor en el pie de página
    "copyright": "Electrodomésticos Jared",
    
    # Oculta el panel de ajustes visuales lateral para mantenerlo limpio
    "show_ui_builder": False,

    # 🔗 NUEVO: BOTÓN DE ACCESO DIRECTO AL SITIO WEB PÚBLICO
    "topmenu_links": [
        # Este botón te lleva al Dashboard principal del panel
        {"name": "Panel Principal",  "url": "admin:index", "permissions": ["auth.view_user"]},
        
        # Este es nuestro nuevo botón mágico que abre tu web en otra pestaña
        {"name": "👁️ Ver Sitio Web", "url": "/", "new_window": True},
    ],
}

JAZZMIN_UI_TWEAKS = {
    # Colores corporativos (Inspirados en tu Landing Page)
    "theme": "pulse",  # Tema moderno con toques morados
    "navbar": "navbar-dark", # Barra superior oscura
    "sidebar": "sidebar-dark-purple", # Menú lateral morado oscuro
    "brand_colour": "navbar-danger", # Título superior con fondo rojo
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "success": "btn-success",
        "danger": "btn-danger",
    }
}